language: cpp

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: API
    - GH_REPO_REF: github.com/OSSIA/API.git
    - secure: DwymbOUVdWgSK0SpNgIrn+6OvwWqc0kGk3S3c+p6gIfKOLHu2sEY7OIIFKdOXs8nwP2INXLQ/wBf3vqpQ5ahuJ6GKk0V4XKizZH7ZfekNtjLQ51QhlvxOx9u1SBXSbiUUVbvIxtRvEfaQpkf1fwapxD2jo0sBXXzNWlNST58clE=

osx_image: xcode8.2
dist: trusty
sudo: required


matrix:
  exclude:
    - os: linux
    - os: osx

  include:
  - os: linux
    env: BUILD_TYPE=Debug OSSIA_STATIC=0
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Debug OSSIA_STATIC=1
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Release OSSIA_STATIC=0
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Release OSSIA_STATIC=1
    dist: trusty

  - os: osx
    env: BUILD_TYPE=Debug OSSIA_STATIC=0
  - os: osx
    env: BUILD_TYPE=Debug OSSIA_STATIC=1
  - os: osx
    env: BUILD_TYPE=Release OSSIA_STATIC=0
  - os: osx
    env: BUILD_TYPE=Release OSSIA_STATIC=1

  - os: linux
    env: BUILD_TYPE=Coverage

  - os: linux
    env: BUILD_TYPE=Docs

before_install:
- "./travis/deps.sh"

script:
- "./travis/build.sh"
